# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connections_pb2 as connections__pb2


class ConnectionsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.person_contacts = channel.unary_unary(
                '/ConnectionsService/person_contacts',
                request_serializer=connections__pb2.ConnectionQuery.SerializeToString,
                response_deserializer=connections__pb2.ConnectionList.FromString,
                )


class ConnectionsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def person_contacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'person_contacts': grpc.unary_unary_rpc_method_handler(
                    servicer.person_contacts,
                    request_deserializer=connections__pb2.ConnectionQuery.FromString,
                    response_serializer=connections__pb2.ConnectionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConnectionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectionsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def person_contacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConnectionsService/person_contacts',
            connections__pb2.ConnectionQuery.SerializeToString,
            connections__pb2.ConnectionList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
